In [3]:
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoModelForSequenceClassification
import torch

In [4]:
tokenizer = AutoTokenizer.from_pretrained("HuggingFaceH4/zephyr-7b-beta")
model = AutoModelForCausalLM.from_pretrained("HuggingFaceH4/zephyr-7b-beta", device_map='auto', load_in_8bit=True)

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards: 100%|██████████| 8/8 [00:11<00:00,  1.38s/it]


In [5]:
text = torch.tensor(tokenizer.encode("Hello, my dog is cute", return_tensors="pt")).to(model.device)

/tmp/ipykernel_5279/554171713.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  text = torch.tensor(tokenizer.encode("Hello, my dog is cute", return_tensors="pt")).to(model.device)


In [6]:
text

tensor([[    1, 22557, 28725,   586,  3914,   349, 17949]], device='cuda:0')

In [7]:
text = "The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Answer with 'Yes' or 'No'\n\n"
tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device))[0], max_new_tokens=50)

/tmp/ipykernel_5279/3489467535.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device))[0], max_new_tokens=50)
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
/home/philko/miniconda3/lib/python3.12/site-packages/transformers/generation/utils.py:1168: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


ValueError: Input length of input_ids is 36, but `max_length` is set to 20. This can lead to unexpected behavior. You should consider increasing `max_length` or, better yet, setting `max_new_tokens`.

In [14]:
torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device)

/tmp/ipykernel_5279/2699246300.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device)


tensor([[    1,   415, 20727,   403,  3292,  5748,   304,   272,  5084, 26705,
         28723, 27611, 28742, 28707,  6557, 28723,    13,    13,  2301,   456,
          4058,  5278,   442,  7087, 28804, 26307,   395,   464, 21436,  1197,
         28742,   442,   464,  3529,  2468, 28742,    13,    13]],
       device='cuda:0')

In [13]:
text = "The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Answer with 'Negative' or 'Positive'\n\n"
tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device), max_new_tokens=1)[0])

/tmp/ipykernel_5279/565880795.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device), max_new_tokens=1)[0])
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


"<s> The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Answer with 'Negative' or 'Positive'\n\nNeg"

In [16]:
reviews = [
    "The pizza was horribe and the staff rude. Won't recommend.",
    "The pasta was undercooked and the service was slow. Not going back.",
    "The salad was wilted and the waiter was dismissive. Avoid at all costs.",
    "The soup was cold and the ambiance was noisy. Not a pleasant experience.",
    "The burger was overcooked and the fries were soggy. I wouldn't suggest this place.",
    "The sushi was not fresh and the staff seemed uninterested. Definitely not worth it.",
    "The steak was tough and the wine was sour. A disappointing meal.",
    "The sandwich was bland and the coffee was lukewarm. Not a fan of this café.",
    "The dessert was stale and the music was too loud. I won't be returning.",
    "The chicken was dry and the vegetables were overcooked. A poor dining experience."
]

In [22]:
batch = tokenizer(reviews, return_tensors="pt", padding=True, truncation=True).to(model.device)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [25]:
a = model.generate(**batch, max_new_tokens=1)

Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


In [15]:
torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device)

/tmp/ipykernel_5279/2699246300.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(tokenizer.encode(text, return_tensors="pt")).to(model.device)


tensor([[    1,   415, 20727,   403,  3292,  5748,   304,   272,  5084, 26705,
         28723, 27611, 28742, 28707,  6557, 28723,    13,    13,  2301,   456,
          4058,  5278,   442,  7087, 28804, 26307,   395,   464, 21436,  1197,
         28742,   442,   464,  3529,  2468, 28742,    13,    13]],
       device='cuda:0')