In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoModelForSequenceClassification
import torch
from torch.functional import F
from torch.utils.data import DataLoader

/home/philko/miniconda3/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model_str = "sshleifer/tiny-gpt2" # "openai-community/gpt2" # "HuggingFaceH4/zephyr-7b-beta" # "openai-community/gpt2"

In [3]:
tokenizer = AutoTokenizer.from_pretrained(model_str)
model = AutoModelForCausalLM.from_pretrained(model_str)
model.to("cuda")

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.


ImportError: Using `bitsandbytes` 8-bit quantization requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes: `pip install -i https://pypi.org/simple/ bitsandbytes`

In [ ]:
text = "The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n"
tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=10)[0])

/tmp/ipykernel_5401/2287509011.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=10)[0])
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


"The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n factors factors factors factors factors factors factors factors factors factors"

In [ ]:
text = "The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n"
tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=10)[0])

/tmp/ipykernel_5401/2287509011.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=10)[0])
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


"The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n factors factors factors factors factors factors factors factors factors factors"

In [ ]:
from datasets import Dataset
from transformers import AutoTokenizer

# Provided list of reviews
reviews = [
    "The pizza was horribe and the staff rude. Won't recommend.",
    "The pasta was undercooked and the service was slow. Not going back.",
    "The salad was wilted and the waiter was dismissive. Avoid at all costs.",
    "The soup was cold and the ambiance was noisy. Not a pleasant experience.",
    "The burger was overcooked and the fries were soggy. I wouldn't suggest this place.",
    "The sushi was not fresh and the staff seemed uninterested. Definitely not worth it.",
    "The steak was tough and the wine was sour. A disappointing meal.",
    "The sandwich was bland and the coffee was lukewarm. Not a fan of this café.",
    "The dessert was stale and the music was too loud. I won't be returning.",
    "The chicken was dry and the vegetables were overcooked. A poor dining experience."
]

# Convert the list to a Hugging Face Dataset
dataset = Dataset.from_dict({'text': reviews})

# Load a tokenizer
# tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

# Set tokenizer padding to the left
tokenizer.padding_side = "left"
# Assuming 'test.tokenizer' is your tokenizer object
if tokenizer.pad_token is None:
    # Add a new pad token if it doesn't exist. This is just an example token.
    # tokenizer.add_special_tokens({'pad_token': '[PAD]'})
    # model.resize_token_embeddings(len(tokenizer))
    tokenizer.pad_token = tokenizer.eos_token

# Tokenize the dataset
def tokenize_function(examples):
    return tokenizer(examples["text"], 
                     padding="max_length", 
                     truncation=True)


tokenized_dataset = dataset.map(tokenize_function, batched=True)

Map: 100%|██████████| 10/10 [00:00<00:00, 1077.17 examples/s]


In [ ]:
text = "The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n"
tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=1)[0])

/tmp/ipykernel_5401/2161875571.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tokenizer.decode(model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=1)[0])
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


"The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n factors"

In [ ]:
text = "The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n"
output = model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=20, output_scores=True, return_dict_in_generate=True)

/tmp/ipykernel_5401/1906926966.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  output = model.generate(torch.tensor(tokenizer.encode(text, return_tensors="pt")).to('cuda'), max_new_tokens=20, output_scores=True, return_dict_in_generate=True)
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
[tokenizer.decode(e) for e in output.sequences]

["The pizza was horribe and the staff rude. Won't recommend.\n\nIs this review positive or negative? Elaborate your decision and start the sentence with 'positive' or 'negative'\n\n factors factors factors factors factors factors factors factors factors factors factors factors factors factors factors factors factors factors factors factors"]

In [ ]:
output.scores[0].shape

torch.Size([1, 50257])

In [ ]:
inp = torch.tensor([tokenizer.encode(text), tokenizer.encode(text)]).to('cuda')

In [ ]:
len(tokenizer)

50257

In [ ]:
tokenizer.pad_token_id

50256

In [ ]:
inp.shape

torch.Size([2, 41])

In [ ]:
output = model.generate(inp, max_new_tokens=1, output_scores=True, return_dict_in_generate=True)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
type(output)

transformers.generation.utils.GenerateDecoderOnlyOutput

In [ ]:
verb_tok = [[tokenizer.encode('positive')[0]], [tokenizer.encode('negative')[0]]]
verb_tok

[[24561], [31591]]

In [ ]:
verb_tok

[[24561], [31591]]

In [ ]:
out_res = torch.cat(list(map(lambda i: output.scores[0][:, verb_tok[i]], range(2))), axis=-1)
out_res

tensor([[ 0.0113, -0.0019],
        [ 0.0113, -0.0019]], device='cuda:0')

In [ ]:
out_res = torch.nn.functional.softmax(out_res, dim=1)

In [ ]:
torch.sum(out_res, axis=1, dtype=torch.float64).tolist()

[1.0000000298023224, 1.0000000298023224]

In [ ]:
sum(map(sum, out_res.cpu().tolist()))

2.0000000596046448

In [ ]:
out_res

tensor([[0.5033, 0.4967],
        [0.5033, 0.4967]], device='cuda:0')

In [ ]:
out_res[:, 0]

tensor([0.5033, 0.5033], device='cuda:0')

In [ ]:

# out_res = torch.nn.functional.softmax(out_res, dim=1)
# # TODO: verbalizer for labtokenizer.encode('positive')els
# class_probs_combined: Dict[str, torch.Tensor] = {k:torch.sum(out_res[:, v], axis=-1) for k, v in i_dict.items()}

In [ ]:
def infer(model, prompt):
    model.eval()
    with torch.no_grad():
        output = model.generate(prompt, max_new_tokens=1, output_scores=True, return_dict_in_generate=True)
    return output.scores[0]

In [ ]:
def calibrate_with_ds(prompt_model, dataloader) -> torch.Tensor:
    r"""Calibrate. See `Paper <https://arxiv.org/abs/2108.02035>`_
    
    Args:
        prompt_model (:obj:`PromptForClassification`): the PromptForClassification model.
        dataloader (:obj:`List`): the dataloader to conduct the calibrate, could be a virtual one, i.e. contain an only-template example.
    
    Return:
        (:obj:`torch.Tensor`) A tensor of shape  (vocabsize) or (mask_num, vocabsize), the logits calculated for each word in the vocabulary
    """
    all_logits = []
    prompt_model.eval()
    for batch in dataloader:
        batch = {k:v.to(prompt_model.device) for k, v in batch.items()}
        logits = infer(model, batch['input_ids'])
        all_logits.append(logits.detach())
    all_logits = torch.cat(all_logits, dim=0)
    return all_logits.mean(dim=0)



In [ ]:
tokenized_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask'])
dataloader = DataLoader(tokenized_dataset, batch_size=1)

In [ ]:
tokenized_dataset

Dataset({
    features: ['text', 'input_ids', 'attention_mask'],
    num_rows: 10
})

In [ ]:
def project(
        label_words_ids, # get from above
        label_words_mask, # get from above
        logits,
        **kwargs,
        ):
    label1 = label_words_ids[0]
    label2 = label_words_ids[1]
    tmp = []
    tmp.append(logits.index_select(label1,axis=-1))
    tmp.append(logits.index_select(label2,axis=-1))
    label_words_logits = paddle.concat(tmp,axis=1).reshape([logits.shape[0],label_words_ids.shape[0],label_words_ids.shape[1]])
    label_words_logits -= 10000*(1-label_words_mask)
    return label_words_logits

In [ ]:
def normalize(logits):
    batch_size = logits.shape[0]
    return F.softmax(logits.reshape([batch_size, -1]), axis=-1).reshape(logits.shape)

In [ ]:
def calibrate(label_words_probs, calibrate_logits, **kwargs):
    shape = label_words_probs.shape
    assert calibrate_logits.dim() ==  1, "self._calibrate_logits are not 1-d tensor"
    calibrate_label_words_probs = normalize(project(calibrate_logits.unsqueeze(0), **kwargs))
    assert calibrate_label_words_probs.shape[1:] == label_words_probs.shape[1:] \
            and calibrate_label_words_probs.shape[0]==1, "shape not match"
    label_words_probs /= (calibrate_label_words_probs+1e-15)
    # normalize # TODO Test the performance
    norm = label_words_probs.reshape(shape[0], -1).sum(dim=-1,keepdim=True) # TODO Test the performance of detaching()
    label_words_probs = label_words_probs.reshape(shape[0], -1) / norm
    label_words_probs = label_words_probs.reshape(*shape)
    return label_words_probs

In [ ]:
type(dataloader)

torch.utils.data.dataloader.DataLoader

In [ ]:
cc_logits = calibrate_with_ds(model, dataloader)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


OutOfMemoryError: CUDA out of memory. Tried to allocate 198.00 MiB. GPU 

In [ ]:
cc_logits = calibrate_with_ds(model, dataloader)
calibrate(None, cc_logits)

AttributeError: 'dict' object has no attribute 'to'